### ISSUE TITLE
Recursive listing doesn't work for remote repo loader

### ISSUE THREAD

**Issue by emilyzheng** [release-engineering/ubi-config#17]
Two issues:
1. recursive in load_all is not used and listing remote repo has been done by _pre_load
2. loading a single yaml doesn't list remote repo recursively, so configuration files not in root path of the repo won't be loaded

**Comment by JayZ12138** [comment]
> recursive in load_all is not used and listing remote repo has been done by _pre_load
I checked this, it's not used in load_all in gitlab loader, but I didn't remove it, as it's defined in the base class, remove it cause pylint problem.
> loading a single yaml doesn't list remote repo recursively, so configuration files not in root path of the 
> repo won't be loaded
I'm not 100% sure what's your point. For the second part, yes, user need to pass the root url to get_loader and since there will be no sub-modules, all config files are stored flat files, so we don't have that concern. 
However, as an open source project, I guess it's a good feature(load files from sub-modules) to support, it's in my original design (removed since not used), maybe we can add it back later.

**Comment by emilyzheng** [comment]
The previous code looks like recursive load from remote repo is supported. But if it's not intended to be used at all, these are not issues any more.

**Comment by emilyzheng** [comment]
The previous code looks like recursive load from remote repo is supported. But if it's not intended to be used at all, these are not issues any more.
