### ISSUE TITLE
__repr__ behavior

### ISSUE THREAD

**Issue by alexandrevicenzi** [release-engineering/ubi-config#26]
Most classes return a pure string on `__repr__`, this can cause debugging problems.

For example `Package` class:

```python
>>> cfg.packages.whitelist[0]
MySQL-python.*
```
It prints a pure string, how in life I will ever know that this is an actual object? It could print:

```python
>>> cfg.packages.whitelist[0]
<Package: MySQL-python.*>
```

`Package` is not a string-like object, it should not act like one. `Modules` does the same.

Also, some classes implement `__repr__` and others not, a pattern should be followed, everything or nothing.

**Comment by JayZ12138** [comment]
@alexandrevicenzi 
Makes sense. 
So, do you think the '<>' is the key part to make you think it's an object?

**Comment by rohanpm** [comment]
The idea with repr at least in part is that it should give you back a representation of the object that you could paste into an interactive Python session to get the same object back.

That's why the documentation mentions you can eval the output of repr:

```
>>> print(repr.__doc__)
repr(object) -> string

Return the canonical string representation of the object.
For most object types, eval(repr(object)) == object.
```

It would be nice to stick with that where practical: `eval(repr(object)) == object`

That would imply it should rather be something like: `Package(name="MySQL-python.*", arches=["x86_64"])`

However, if it would cost non-trivial code to accomplish that, then it's probably not worth it.

If you don't want to implement that full repr, then indeed surrounding with `<>` seems to be the convention, e.g. compare with:

```
print(repr(object()))
<object object at 0x7ff8f57380a0>
```

**Comment by alexandrevicenzi** [comment]
@JayZ12138 I agree with @rohanpm, at least we should include `<>`.
