### ISSUE TITLE
Support for getting config by content set label

### ISSUE THREAD

**Issue by rbikar** [release-engineering/ubi-config#42]
#### Summary
Goal of this issue is to add support for getting config by content set label. So caller doesn't need to know name of config file or doesn't want to get all config available.

#### Issue Type
- Feature Request

#### Desired behavior
- ubi-config accepts queries for config by content set label
- public methods created are properly documented

**Comment by rohanpm** [comment]
Can we get some more info on what is the purpose of this API?  In the current PR for this, I see the proposed implementation would retrieve only a *single* arbitrary piece of config (rather than all config matching the content set label).  I think that it would be needed to return all pieces of matching config, but the use-case isn't adequately explained here.

Actually, can we revisit if this is needed at all?  My understanding is that the issue was connected with a use-case like this:

- we are going to publish content to N Pulp repos
- due to that, we will want to regenerate all related UBI repos
- since each Pulp repo knows which content set it relates to, we can get content sets for the Pulp repos, then get UBI config for all those content sets, in order to know which UBI repos are relevant

But, I think this idea predated some other developments, in particular DELIVERY-7356 which adds population_sources note, making it possible to more directly jump between a Pulp repo and corresponding UBI repo.

Another use-case might have been asking for UBI population to run only for specific content sets, but even that I think can be achieved with the population_sources note now?  1 - find Pulp repos belonging to those content sets, 2 - find Pulp repos with population_sources containing repos from (1) ?

So who wants to call this API, why, and how?  Can the issue description please have a realistic example of calling this API?

**Comment by rbikar** [comment]
The intended use case is:
- ubipop calls ubi-config to load config for specific content set
- reason was to save some network load but I guess it's not a problem.

I revised how fetching is done in ubipop now, I think filtering by content set label can be done on ubipop side easily so we don't have to do anything in ubi-config.

For matching all config for one content set I haven't filed an issue yet.
Just fyi at the time of writing there is only one config for one content set label, but this will change with changing branching scheme that will be based on versions. Then it's expected to have more config files for one content set, then ubipop will select the correct one.

**Comment by nathanegillett** [comment]
So, if this feature is not needed in ubi-config can we close the issue here and in JIRA? The approach I've taken here can easily move to ubipop.

**Comment by rbikar** [comment]
I'll update description of https://github.com/release-engineering/ubi-population-tool/issues/121 in order to have more precise requirements for this feature.

**Comment by JayZ12138** [comment]
I'm closing this issue because we don't need this feature.
